{% set name = "hexdump" %}
{% set version = "3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hexdump-{{ version }}.zip
  sha256: d781a43b0c16ace3f9366aade73e8ad3a7bd5137d58f0b45ab2d3f54876f20db

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - hexdump
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/hexdump
  summary: dump binary data to hex format and restore from there
  license: LicenseRef-Public-Domain
  license_family: PUBLIC-DOMAIN
  license_file: LICENSE.txt
  dev_url: https://bitbucket.org/techtonik/hexdump

extra:
  recipe-maintainers:
    - goanpeca
